"""new Order table

Revision ID: 09f03588f184
Revises: 78f6e27b6bf5
Create Date: 2023-08-21 18:45:45.585114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f03588f184'
down_revision: Union[str, None] = '78f6e27b6bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('pizza_quantity', sa.Integer(), nullable=False),
    sa.Column('pizza_price', sa.Float(), nullable=False),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('notes', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'notes')
    op.drop_table('order')
    # ### end Alembic commands ###
